name: Automated Testing

on:
  push:
    branches:
      - main  # Modify this to match your branch name
  pull_request:
    branches:
      - main  # Modify this to match your branch name

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest  # Modify the runner as per your requirements

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Modify this to match your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tests with tox
        run: tox
